### ISSUE TITLE
"progressive" in what sense? 

### ISSUE THREAD

**Issue by jezmck** [thinker3197/progressively#3]
Does it depend on smaller versions of the images existing? 

Are you just avoiding using the word "lazy"? 

I am on mobile, so difficult to check, but think it should be part of the description.

**Comment by thinker3197** [comment]
Progressive rendering is different from lazy loading. In lazy loading you wait for the content to get fetched from the server and then display it. However in progressive loading, we render the image in stages, so that the user won't be seeing a blank screen or loader. 
Progressively does this by requesting a smaller version of the image (which gets fetched quickly) and display it to the user while the original image is fetched asynchronously and then replaced with the smaller one using the progressive blur effect.

**Comment by thinker3197** [comment]
Closing the issue
